name: Manual run workflow for testing
on:
  workflow_dispatch
permissions:
  pull-requests: write
jobs:
  build:
    name: Manuyally triggered job 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello work"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
